// Code generated by go-swagger; DO NOT EDIT.

package ordering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrderingListInfoParams creates a new OrderingListInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderingListInfoParams() *OrderingListInfoParams {
	return &OrderingListInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderingListInfoParamsWithTimeout creates a new OrderingListInfoParams object
// with the ability to set a timeout on a request.
func NewOrderingListInfoParamsWithTimeout(timeout time.Duration) *OrderingListInfoParams {
	return &OrderingListInfoParams{
		timeout: timeout,
	}
}

// NewOrderingListInfoParamsWithContext creates a new OrderingListInfoParams object
// with the ability to set a context for a request.
func NewOrderingListInfoParamsWithContext(ctx context.Context) *OrderingListInfoParams {
	return &OrderingListInfoParams{
		Context: ctx,
	}
}

// NewOrderingListInfoParamsWithHTTPClient creates a new OrderingListInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderingListInfoParamsWithHTTPClient(client *http.Client) *OrderingListInfoParams {
	return &OrderingListInfoParams{
		HTTPClient: client,
	}
}

/*
OrderingListInfoParams contains all the parameters to send to the API endpoint

	for the ordering list info operation.

	Typically these are written to a http.Request.
*/
type OrderingListInfoParams struct {

	// Body.
	Body OrderingListInfoBody

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ordering list info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingListInfoParams) WithDefaults() *OrderingListInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ordering list info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingListInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ordering list info params
func (o *OrderingListInfoParams) WithTimeout(timeout time.Duration) *OrderingListInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ordering list info params
func (o *OrderingListInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ordering list info params
func (o *OrderingListInfoParams) WithContext(ctx context.Context) *OrderingListInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ordering list info params
func (o *OrderingListInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ordering list info params
func (o *OrderingListInfoParams) WithHTTPClient(client *http.Client) *OrderingListInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ordering list info params
func (o *OrderingListInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ordering list info params
func (o *OrderingListInfoParams) WithBody(body OrderingListInfoBody) *OrderingListInfoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ordering list info params
func (o *OrderingListInfoParams) SetBody(body OrderingListInfoBody) {
	o.Body = body
}

// WithChannelName adds the channelName to the ordering list info params
func (o *OrderingListInfoParams) WithChannelName(channelName string) *OrderingListInfoParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the ordering list info params
func (o *OrderingListInfoParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *OrderingListInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
