// Code generated by go-swagger; DO NOT EDIT.

package ordering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrderingJoinParams creates a new OrderingJoinParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderingJoinParams() *OrderingJoinParams {
	return &OrderingJoinParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderingJoinParamsWithTimeout creates a new OrderingJoinParams object
// with the ability to set a timeout on a request.
func NewOrderingJoinParamsWithTimeout(timeout time.Duration) *OrderingJoinParams {
	return &OrderingJoinParams{
		timeout: timeout,
	}
}

// NewOrderingJoinParamsWithContext creates a new OrderingJoinParams object
// with the ability to set a context for a request.
func NewOrderingJoinParamsWithContext(ctx context.Context) *OrderingJoinParams {
	return &OrderingJoinParams{
		Context: ctx,
	}
}

// NewOrderingJoinParamsWithHTTPClient creates a new OrderingJoinParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderingJoinParamsWithHTTPClient(client *http.Client) *OrderingJoinParams {
	return &OrderingJoinParams{
		HTTPClient: client,
	}
}

/*
OrderingJoinParams contains all the parameters to send to the API endpoint

	for the ordering join operation.

	Typically these are written to a http.Request.
*/
type OrderingJoinParams struct {

	// Body.
	Body OrderingJoinBody

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ordering join params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingJoinParams) WithDefaults() *OrderingJoinParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ordering join params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingJoinParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ordering join params
func (o *OrderingJoinParams) WithTimeout(timeout time.Duration) *OrderingJoinParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ordering join params
func (o *OrderingJoinParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ordering join params
func (o *OrderingJoinParams) WithContext(ctx context.Context) *OrderingJoinParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ordering join params
func (o *OrderingJoinParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ordering join params
func (o *OrderingJoinParams) WithHTTPClient(client *http.Client) *OrderingJoinParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ordering join params
func (o *OrderingJoinParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ordering join params
func (o *OrderingJoinParams) WithBody(body OrderingJoinBody) *OrderingJoinParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ordering join params
func (o *OrderingJoinParams) SetBody(body OrderingJoinBody) {
	o.Body = body
}

// WithChannelName adds the channelName to the ordering join params
func (o *OrderingJoinParams) WithChannelName(channelName string) *OrderingJoinParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the ordering join params
func (o *OrderingJoinParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *OrderingJoinParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
