// Code generated by go-swagger; DO NOT EDIT.

package ordering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new ordering API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for ordering API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	OrderingJoin(params *OrderingJoinParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OrderingJoinOK, error)

	OrderingListInfo(params *OrderingListInfoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OrderingListInfoOK, error)

	OrderingRemove(params *OrderingRemoveParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OrderingRemoveOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
OrderingJoin joins orderer to channel
*/
func (a *Client) OrderingJoin(params *OrderingJoinParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OrderingJoinOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrderingJoinParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "orderingJoin",
		Method:             "POST",
		PathPattern:        "/v1/ordering/{channelName}/join",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrderingJoinReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrderingJoinOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrderingJoinDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
OrderingListInfo lists of channels for orderer
*/
func (a *Client) OrderingListInfo(params *OrderingListInfoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OrderingListInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrderingListInfoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "orderingListInfo",
		Method:             "POST",
		PathPattern:        "/v1/ordering/{channelName}/list",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrderingListInfoReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrderingListInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrderingListInfoDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
OrderingRemove removes orderer from channel
*/
func (a *Client) OrderingRemove(params *OrderingRemoveParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OrderingRemoveOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrderingRemoveParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "orderingRemove",
		Method:             "POST",
		PathPattern:        "/v1/ordering/{channelName}/remove",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrderingRemoveReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrderingRemoveOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrderingRemoveDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
