// Code generated by go-swagger; DO NOT EDIT.

package discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDiscoveryPeersParams creates a new DiscoveryPeersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDiscoveryPeersParams() *DiscoveryPeersParams {
	return &DiscoveryPeersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDiscoveryPeersParamsWithTimeout creates a new DiscoveryPeersParams object
// with the ability to set a timeout on a request.
func NewDiscoveryPeersParamsWithTimeout(timeout time.Duration) *DiscoveryPeersParams {
	return &DiscoveryPeersParams{
		timeout: timeout,
	}
}

// NewDiscoveryPeersParamsWithContext creates a new DiscoveryPeersParams object
// with the ability to set a context for a request.
func NewDiscoveryPeersParamsWithContext(ctx context.Context) *DiscoveryPeersParams {
	return &DiscoveryPeersParams{
		Context: ctx,
	}
}

// NewDiscoveryPeersParamsWithHTTPClient creates a new DiscoveryPeersParams object
// with the ability to set a custom HTTPClient for a request.
func NewDiscoveryPeersParamsWithHTTPClient(client *http.Client) *DiscoveryPeersParams {
	return &DiscoveryPeersParams{
		HTTPClient: client,
	}
}

/*
DiscoveryPeersParams contains all the parameters to send to the API endpoint

	for the discovery peers operation.

	Typically these are written to a http.Request.
*/
type DiscoveryPeersParams struct {

	// Body.
	Body interface{}

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the discovery peers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DiscoveryPeersParams) WithDefaults() *DiscoveryPeersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the discovery peers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DiscoveryPeersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the discovery peers params
func (o *DiscoveryPeersParams) WithTimeout(timeout time.Duration) *DiscoveryPeersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the discovery peers params
func (o *DiscoveryPeersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the discovery peers params
func (o *DiscoveryPeersParams) WithContext(ctx context.Context) *DiscoveryPeersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the discovery peers params
func (o *DiscoveryPeersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the discovery peers params
func (o *DiscoveryPeersParams) WithHTTPClient(client *http.Client) *DiscoveryPeersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the discovery peers params
func (o *DiscoveryPeersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the discovery peers params
func (o *DiscoveryPeersParams) WithBody(body interface{}) *DiscoveryPeersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the discovery peers params
func (o *DiscoveryPeersParams) SetBody(body interface{}) {
	o.Body = body
}

// WithChannelName adds the channelName to the discovery peers params
func (o *DiscoveryPeersParams) WithChannelName(channelName string) *DiscoveryPeersParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the discovery peers params
func (o *DiscoveryPeersParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *DiscoveryPeersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
