// Code generated by go-swagger; DO NOT EDIT.

package chaincode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/atomyze-foundation/hlf-control-plane/test/integration/models"
)

// NewChaincodeInstallParams creates a new ChaincodeInstallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChaincodeInstallParams() *ChaincodeInstallParams {
	return &ChaincodeInstallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChaincodeInstallParamsWithTimeout creates a new ChaincodeInstallParams object
// with the ability to set a timeout on a request.
func NewChaincodeInstallParamsWithTimeout(timeout time.Duration) *ChaincodeInstallParams {
	return &ChaincodeInstallParams{
		timeout: timeout,
	}
}

// NewChaincodeInstallParamsWithContext creates a new ChaincodeInstallParams object
// with the ability to set a context for a request.
func NewChaincodeInstallParamsWithContext(ctx context.Context) *ChaincodeInstallParams {
	return &ChaincodeInstallParams{
		Context: ctx,
	}
}

// NewChaincodeInstallParamsWithHTTPClient creates a new ChaincodeInstallParams object
// with the ability to set a custom HTTPClient for a request.
func NewChaincodeInstallParamsWithHTTPClient(client *http.Client) *ChaincodeInstallParams {
	return &ChaincodeInstallParams{
		HTTPClient: client,
	}
}

/*
ChaincodeInstallParams contains all the parameters to send to the API endpoint

	for the chaincode install operation.

	Typically these are written to a http.Request.
*/
type ChaincodeInstallParams struct {

	/* Body.

	   Request for downloading and installation of chaincodes
	*/
	Body *models.ProtoChaincodeInstallRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the chaincode install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChaincodeInstallParams) WithDefaults() *ChaincodeInstallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the chaincode install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChaincodeInstallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the chaincode install params
func (o *ChaincodeInstallParams) WithTimeout(timeout time.Duration) *ChaincodeInstallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the chaincode install params
func (o *ChaincodeInstallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the chaincode install params
func (o *ChaincodeInstallParams) WithContext(ctx context.Context) *ChaincodeInstallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the chaincode install params
func (o *ChaincodeInstallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the chaincode install params
func (o *ChaincodeInstallParams) WithHTTPClient(client *http.Client) *ChaincodeInstallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the chaincode install params
func (o *ChaincodeInstallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the chaincode install params
func (o *ChaincodeInstallParams) WithBody(body *models.ProtoChaincodeInstallRequest) *ChaincodeInstallParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the chaincode install params
func (o *ChaincodeInstallParams) SetBody(body *models.ProtoChaincodeInstallRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ChaincodeInstallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
