// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DiscoveryEndpoints Endpoints is a list of Endpoint(s)
//
// swagger:model discoveryEndpoints
type DiscoveryEndpoints struct {

	// endpoint
	Endpoint []*DiscoveryEndpoint `json:"endpoint"`
}

// Validate validates this discovery endpoints
func (m *DiscoveryEndpoints) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiscoveryEndpoints) validateEndpoint(formats strfmt.Registry) error {
	if swag.IsZero(m.Endpoint) { // not required
		return nil
	}

	for i := 0; i < len(m.Endpoint); i++ {
		if swag.IsZero(m.Endpoint[i]) { // not required
			continue
		}

		if m.Endpoint[i] != nil {
			if err := m.Endpoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("endpoint" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("endpoint" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this discovery endpoints based on the context it is used
func (m *DiscoveryEndpoints) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEndpoint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiscoveryEndpoints) contextValidateEndpoint(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Endpoint); i++ {

		if m.Endpoint[i] != nil {

			if swag.IsZero(m.Endpoint[i]) { // not required
				return nil
			}

			if err := m.Endpoint[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("endpoint" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("endpoint" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiscoveryEndpoints) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiscoveryEndpoints) UnmarshalBinary(b []byte) error {
	var res DiscoveryEndpoints
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
