// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MspFabricCryptoConfig FabricCryptoConfig contains configuration parameters
// for the cryptographic algorithms used by the MSP
// this configuration refers to
//
// swagger:model mspFabricCryptoConfig
type MspFabricCryptoConfig struct {

	// IdentityIdentifierHashFunction is a string representing the hash function
	// to be used during the computation of the identity identifier of an MSP identity.
	// Allowed values are "SHA256", "SHA384" and "SHA3_256", "SHA3_384".
	IdentityIdentifierHashFunction string `json:"identityIdentifierHashFunction,omitempty"`

	// SignatureHashFamily is a string representing the hash family to be used
	// during sign and verify operations.
	// Allowed values are "SHA2" and "SHA3".
	SignatureHashFamily string `json:"signatureHashFamily,omitempty"`
}

// Validate validates this msp fabric crypto config
func (m *MspFabricCryptoConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this msp fabric crypto config based on context it is used
func (m *MspFabricCryptoConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MspFabricCryptoConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MspFabricCryptoConfig) UnmarshalBinary(b []byte) error {
	var res MspFabricCryptoConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
