// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MspFabricOUIdentifier FabricOUIdentifier represents an organizational unit and
// its related chain of trust identifier.
//
// swagger:model mspFabricOUIdentifier
type MspFabricOUIdentifier struct {

	// Certificate represents the second certificate in a certification chain.
	// (Notice that the first certificate in a certification chain is supposed
	// to be the certificate of an identity).
	// It must correspond to the certificate of root or intermediate CA
	// recognized by the MSP this message belongs to.
	// Starting from this certificate, a certification chain is computed
	// and bound to the OrganizationUnitIdentifier specified
	// Format: byte
	Certificate strfmt.Base64 `json:"certificate,omitempty"`

	// OrganizationUnitIdentifier defines the organizational unit under the
	// MSP identified with MSPIdentifier
	OrganizationalUnitIdentifier string `json:"organizationalUnitIdentifier,omitempty"`
}

// Validate validates this msp fabric o u identifier
func (m *MspFabricOUIdentifier) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this msp fabric o u identifier based on context it is used
func (m *MspFabricOUIdentifier) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MspFabricOUIdentifier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MspFabricOUIdentifier) UnmarshalBinary(b []byte) error {
	var res MspFabricOUIdentifier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
