// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderingRequestJoined ordering request joined
//
// swagger:model OrderingRequestJoined
type OrderingRequestJoined struct {

	// host
	Host string `json:"host,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`
}

// Validate validates this ordering request joined
func (m *OrderingRequestJoined) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ordering request joined based on context it is used
func (m *OrderingRequestJoined) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderingRequestJoined) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderingRequestJoined) UnmarshalBinary(b []byte) error {
	var res OrderingRequestJoined
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
