// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderingListInfoResponseChannelInfo ordering list info response channel info
//
// swagger:model OrderingListInfoResponseChannelInfo
type OrderingListInfoResponseChannelInfo struct {

	// consensus relation
	ConsensusRelation string `json:"consensusRelation,omitempty"`

	// height
	Height string `json:"height,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this ordering list info response channel info
func (m *OrderingListInfoResponseChannelInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ordering list info response channel info based on context it is used
func (m *OrderingListInfoResponseChannelInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderingListInfoResponseChannelInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderingListInfoResponseChannelInfo) UnmarshalBinary(b []byte) error {
	var res OrderingListInfoResponseChannelInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
