// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoLifecycleFullResponse proto lifecycle full response
//
// swagger:model protoLifecycleFullResponse
type ProtoLifecycleFullResponse struct {

	// approvals
	Approvals map[string]bool `json:"approvals,omitempty"`

	// committed
	Committed bool `json:"committed,omitempty"`
}

// Validate validates this proto lifecycle full response
func (m *ProtoLifecycleFullResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this proto lifecycle full response based on context it is used
func (m *ProtoLifecycleFullResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoLifecycleFullResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoLifecycleFullResponse) UnmarshalBinary(b []byte) error {
	var res ProtoLifecycleFullResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
