// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoLifecycleStatusResponse proto lifecycle status response
//
// swagger:model protoLifecycleStatusResponse
type ProtoLifecycleStatusResponse struct {

	// chaincodes
	Chaincodes []*ProtoLifecycleChaincode `json:"chaincodes"`
}

// Validate validates this proto lifecycle status response
func (m *ProtoLifecycleStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChaincodes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoLifecycleStatusResponse) validateChaincodes(formats strfmt.Registry) error {
	if swag.IsZero(m.Chaincodes) { // not required
		return nil
	}

	for i := 0; i < len(m.Chaincodes); i++ {
		if swag.IsZero(m.Chaincodes[i]) { // not required
			continue
		}

		if m.Chaincodes[i] != nil {
			if err := m.Chaincodes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chaincodes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chaincodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this proto lifecycle status response based on the context it is used
func (m *ProtoLifecycleStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChaincodes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoLifecycleStatusResponse) contextValidateChaincodes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Chaincodes); i++ {

		if m.Chaincodes[i] != nil {

			if swag.IsZero(m.Chaincodes[i]) { // not required
				return nil
			}

			if err := m.Chaincodes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chaincodes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chaincodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProtoLifecycleStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoLifecycleStatusResponse) UnmarshalBinary(b []byte) error {
	var res ProtoLifecycleStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
