// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoConfigAnchorModifyResponse proto config anchor modify response
//
// swagger:model protoConfigAnchorModifyResponse
type ProtoConfigAnchorModifyResponse struct {

	// deleted
	Deleted []*ProtosAnchorPeer `json:"deleted"`

	// existed
	Existed []*ProtosAnchorPeer `json:"existed"`

	// new
	New []*ProtosAnchorPeer `json:"new"`
}

// Validate validates this proto config anchor modify response
func (m *ProtoConfigAnchorModifyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeleted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExisted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNew(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoConfigAnchorModifyResponse) validateDeleted(formats strfmt.Registry) error {
	if swag.IsZero(m.Deleted) { // not required
		return nil
	}

	for i := 0; i < len(m.Deleted); i++ {
		if swag.IsZero(m.Deleted[i]) { // not required
			continue
		}

		if m.Deleted[i] != nil {
			if err := m.Deleted[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deleted" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deleted" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProtoConfigAnchorModifyResponse) validateExisted(formats strfmt.Registry) error {
	if swag.IsZero(m.Existed) { // not required
		return nil
	}

	for i := 0; i < len(m.Existed); i++ {
		if swag.IsZero(m.Existed[i]) { // not required
			continue
		}

		if m.Existed[i] != nil {
			if err := m.Existed[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("existed" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("existed" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProtoConfigAnchorModifyResponse) validateNew(formats strfmt.Registry) error {
	if swag.IsZero(m.New) { // not required
		return nil
	}

	for i := 0; i < len(m.New); i++ {
		if swag.IsZero(m.New[i]) { // not required
			continue
		}

		if m.New[i] != nil {
			if err := m.New[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("new" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("new" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this proto config anchor modify response based on the context it is used
func (m *ProtoConfigAnchorModifyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeleted(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExisted(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNew(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoConfigAnchorModifyResponse) contextValidateDeleted(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Deleted); i++ {

		if m.Deleted[i] != nil {

			if swag.IsZero(m.Deleted[i]) { // not required
				return nil
			}

			if err := m.Deleted[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deleted" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deleted" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProtoConfigAnchorModifyResponse) contextValidateExisted(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Existed); i++ {

		if m.Existed[i] != nil {

			if swag.IsZero(m.Existed[i]) { // not required
				return nil
			}

			if err := m.Existed[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("existed" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("existed" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProtoConfigAnchorModifyResponse) contextValidateNew(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.New); i++ {

		if m.New[i] != nil {

			if swag.IsZero(m.New[i]) { // not required
				return nil
			}

			if err := m.New[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("new" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("new" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProtoConfigAnchorModifyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoConfigAnchorModifyResponse) UnmarshalBinary(b []byte) error {
	var res ProtoConfigAnchorModifyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
