// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoConfigOrderingListResponse proto config ordering list response
//
// swagger:model protoConfigOrderingListResponse
type ProtoConfigOrderingListResponse struct {

	// consensus
	Consensus *ProtoConsensusType `json:"consensus,omitempty"`

	// orderers
	Orderers []*ProtoOrderer `json:"orderers"`
}

// Validate validates this proto config ordering list response
func (m *ProtoConfigOrderingListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsensus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoConfigOrderingListResponse) validateConsensus(formats strfmt.Registry) error {
	if swag.IsZero(m.Consensus) { // not required
		return nil
	}

	if m.Consensus != nil {
		if err := m.Consensus.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("consensus")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("consensus")
			}
			return err
		}
	}

	return nil
}

func (m *ProtoConfigOrderingListResponse) validateOrderers(formats strfmt.Registry) error {
	if swag.IsZero(m.Orderers) { // not required
		return nil
	}

	for i := 0; i < len(m.Orderers); i++ {
		if swag.IsZero(m.Orderers[i]) { // not required
			continue
		}

		if m.Orderers[i] != nil {
			if err := m.Orderers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("orderers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this proto config ordering list response based on the context it is used
func (m *ProtoConfigOrderingListResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConsensus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOrderers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProtoConfigOrderingListResponse) contextValidateConsensus(ctx context.Context, formats strfmt.Registry) error {

	if m.Consensus != nil {

		if swag.IsZero(m.Consensus) { // not required
			return nil
		}

		if err := m.Consensus.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("consensus")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("consensus")
			}
			return err
		}
	}

	return nil
}

func (m *ProtoConfigOrderingListResponse) contextValidateOrderers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Orderers); i++ {

		if m.Orderers[i] != nil {

			if swag.IsZero(m.Orderers[i]) { // not required
				return nil
			}

			if err := m.Orderers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("orderers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProtoConfigOrderingListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoConfigOrderingListResponse) UnmarshalBinary(b []byte) error {
	var res ProtoConfigOrderingListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
