// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoLifecycleInitRequest proto lifecycle init request
//
// swagger:model protoLifecycleInitRequest
type ProtoLifecycleInitRequest struct {

	// chaincode name
	ChaincodeName string `json:"chaincodeName,omitempty"`

	// channel name
	ChannelName string `json:"channelName,omitempty"`

	// init args
	InitArgs []string `json:"initArgs"`
}

// Validate validates this proto lifecycle init request
func (m *ProtoLifecycleInitRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this proto lifecycle init request based on context it is used
func (m *ProtoLifecycleInitRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoLifecycleInitRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoLifecycleInitRequest) UnmarshalBinary(b []byte) error {
	var res ProtoLifecycleInitRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
