// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtoLifecycleChaincode proto lifecycle chaincode
//
// swagger:model protoLifecycleChaincode
type ProtoLifecycleChaincode struct {

	// init required
	InitRequired bool `json:"initRequired,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// sequence
	Sequence string `json:"sequence,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this proto lifecycle chaincode
func (m *ProtoLifecycleChaincode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this proto lifecycle chaincode based on context it is used
func (m *ProtoLifecycleChaincode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoLifecycleChaincode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtoLifecycleChaincode) UnmarshalBinary(b []byte) error {
	var res ProtoLifecycleChaincode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
