// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAnchorPeerModifyParams creates a new AnchorPeerModifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAnchorPeerModifyParams() *AnchorPeerModifyParams {
	return &AnchorPeerModifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAnchorPeerModifyParamsWithTimeout creates a new AnchorPeerModifyParams object
// with the ability to set a timeout on a request.
func NewAnchorPeerModifyParamsWithTimeout(timeout time.Duration) *AnchorPeerModifyParams {
	return &AnchorPeerModifyParams{
		timeout: timeout,
	}
}

// NewAnchorPeerModifyParamsWithContext creates a new AnchorPeerModifyParams object
// with the ability to set a context for a request.
func NewAnchorPeerModifyParamsWithContext(ctx context.Context) *AnchorPeerModifyParams {
	return &AnchorPeerModifyParams{
		Context: ctx,
	}
}

// NewAnchorPeerModifyParamsWithHTTPClient creates a new AnchorPeerModifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewAnchorPeerModifyParamsWithHTTPClient(client *http.Client) *AnchorPeerModifyParams {
	return &AnchorPeerModifyParams{
		HTTPClient: client,
	}
}

/*
AnchorPeerModifyParams contains all the parameters to send to the API endpoint

	for the anchor peer modify operation.

	Typically these are written to a http.Request.
*/
type AnchorPeerModifyParams struct {

	// Body.
	Body AnchorPeerModifyBody

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the anchor peer modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AnchorPeerModifyParams) WithDefaults() *AnchorPeerModifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the anchor peer modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AnchorPeerModifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the anchor peer modify params
func (o *AnchorPeerModifyParams) WithTimeout(timeout time.Duration) *AnchorPeerModifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the anchor peer modify params
func (o *AnchorPeerModifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the anchor peer modify params
func (o *AnchorPeerModifyParams) WithContext(ctx context.Context) *AnchorPeerModifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the anchor peer modify params
func (o *AnchorPeerModifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the anchor peer modify params
func (o *AnchorPeerModifyParams) WithHTTPClient(client *http.Client) *AnchorPeerModifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the anchor peer modify params
func (o *AnchorPeerModifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the anchor peer modify params
func (o *AnchorPeerModifyParams) WithBody(body AnchorPeerModifyBody) *AnchorPeerModifyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the anchor peer modify params
func (o *AnchorPeerModifyParams) SetBody(body AnchorPeerModifyBody) {
	o.Body = body
}

// WithChannelName adds the channelName to the anchor peer modify params
func (o *AnchorPeerModifyParams) WithChannelName(channelName string) *AnchorPeerModifyParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the anchor peer modify params
func (o *AnchorPeerModifyParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *AnchorPeerModifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
