// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrderingConfigDeleteParams creates a new OrderingConfigDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderingConfigDeleteParams() *OrderingConfigDeleteParams {
	return &OrderingConfigDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderingConfigDeleteParamsWithTimeout creates a new OrderingConfigDeleteParams object
// with the ability to set a timeout on a request.
func NewOrderingConfigDeleteParamsWithTimeout(timeout time.Duration) *OrderingConfigDeleteParams {
	return &OrderingConfigDeleteParams{
		timeout: timeout,
	}
}

// NewOrderingConfigDeleteParamsWithContext creates a new OrderingConfigDeleteParams object
// with the ability to set a context for a request.
func NewOrderingConfigDeleteParamsWithContext(ctx context.Context) *OrderingConfigDeleteParams {
	return &OrderingConfigDeleteParams{
		Context: ctx,
	}
}

// NewOrderingConfigDeleteParamsWithHTTPClient creates a new OrderingConfigDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderingConfigDeleteParamsWithHTTPClient(client *http.Client) *OrderingConfigDeleteParams {
	return &OrderingConfigDeleteParams{
		HTTPClient: client,
	}
}

/*
OrderingConfigDeleteParams contains all the parameters to send to the API endpoint

	for the ordering config delete operation.

	Typically these are written to a http.Request.
*/
type OrderingConfigDeleteParams struct {

	// Body.
	Body OrderingConfigDeleteBody

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ordering config delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingConfigDeleteParams) WithDefaults() *OrderingConfigDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ordering config delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingConfigDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ordering config delete params
func (o *OrderingConfigDeleteParams) WithTimeout(timeout time.Duration) *OrderingConfigDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ordering config delete params
func (o *OrderingConfigDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ordering config delete params
func (o *OrderingConfigDeleteParams) WithContext(ctx context.Context) *OrderingConfigDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ordering config delete params
func (o *OrderingConfigDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ordering config delete params
func (o *OrderingConfigDeleteParams) WithHTTPClient(client *http.Client) *OrderingConfigDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ordering config delete params
func (o *OrderingConfigDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ordering config delete params
func (o *OrderingConfigDeleteParams) WithBody(body OrderingConfigDeleteBody) *OrderingConfigDeleteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ordering config delete params
func (o *OrderingConfigDeleteParams) SetBody(body OrderingConfigDeleteBody) {
	o.Body = body
}

// WithChannelName adds the channelName to the ordering config delete params
func (o *OrderingConfigDeleteParams) WithChannelName(channelName string) *OrderingConfigDeleteParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the ordering config delete params
func (o *OrderingConfigDeleteParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *OrderingConfigDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
