// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrderingConfigAddParams creates a new OrderingConfigAddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrderingConfigAddParams() *OrderingConfigAddParams {
	return &OrderingConfigAddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrderingConfigAddParamsWithTimeout creates a new OrderingConfigAddParams object
// with the ability to set a timeout on a request.
func NewOrderingConfigAddParamsWithTimeout(timeout time.Duration) *OrderingConfigAddParams {
	return &OrderingConfigAddParams{
		timeout: timeout,
	}
}

// NewOrderingConfigAddParamsWithContext creates a new OrderingConfigAddParams object
// with the ability to set a context for a request.
func NewOrderingConfigAddParamsWithContext(ctx context.Context) *OrderingConfigAddParams {
	return &OrderingConfigAddParams{
		Context: ctx,
	}
}

// NewOrderingConfigAddParamsWithHTTPClient creates a new OrderingConfigAddParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrderingConfigAddParamsWithHTTPClient(client *http.Client) *OrderingConfigAddParams {
	return &OrderingConfigAddParams{
		HTTPClient: client,
	}
}

/*
OrderingConfigAddParams contains all the parameters to send to the API endpoint

	for the ordering config add operation.

	Typically these are written to a http.Request.
*/
type OrderingConfigAddParams struct {

	// Body.
	Body OrderingConfigAddBody

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ordering config add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingConfigAddParams) WithDefaults() *OrderingConfigAddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ordering config add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrderingConfigAddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ordering config add params
func (o *OrderingConfigAddParams) WithTimeout(timeout time.Duration) *OrderingConfigAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ordering config add params
func (o *OrderingConfigAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ordering config add params
func (o *OrderingConfigAddParams) WithContext(ctx context.Context) *OrderingConfigAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ordering config add params
func (o *OrderingConfigAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ordering config add params
func (o *OrderingConfigAddParams) WithHTTPClient(client *http.Client) *OrderingConfigAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ordering config add params
func (o *OrderingConfigAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ordering config add params
func (o *OrderingConfigAddParams) WithBody(body OrderingConfigAddBody) *OrderingConfigAddParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ordering config add params
func (o *OrderingConfigAddParams) SetBody(body OrderingConfigAddBody) {
	o.Body = body
}

// WithChannelName adds the channelName to the ordering config add params
func (o *OrderingConfigAddParams) WithChannelName(channelName string) *OrderingConfigAddParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the ordering config add params
func (o *OrderingConfigAddParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *OrderingConfigAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
