// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSmartBftSetParams creates a new SmartBftSetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSmartBftSetParams() *SmartBftSetParams {
	return &SmartBftSetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSmartBftSetParamsWithTimeout creates a new SmartBftSetParams object
// with the ability to set a timeout on a request.
func NewSmartBftSetParamsWithTimeout(timeout time.Duration) *SmartBftSetParams {
	return &SmartBftSetParams{
		timeout: timeout,
	}
}

// NewSmartBftSetParamsWithContext creates a new SmartBftSetParams object
// with the ability to set a context for a request.
func NewSmartBftSetParamsWithContext(ctx context.Context) *SmartBftSetParams {
	return &SmartBftSetParams{
		Context: ctx,
	}
}

// NewSmartBftSetParamsWithHTTPClient creates a new SmartBftSetParams object
// with the ability to set a custom HTTPClient for a request.
func NewSmartBftSetParamsWithHTTPClient(client *http.Client) *SmartBftSetParams {
	return &SmartBftSetParams{
		HTTPClient: client,
	}
}

/*
SmartBftSetParams contains all the parameters to send to the API endpoint

	for the smart bft set operation.

	Typically these are written to a http.Request.
*/
type SmartBftSetParams struct {

	// Body.
	Body SmartBftSetBody

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the smart bft set params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SmartBftSetParams) WithDefaults() *SmartBftSetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the smart bft set params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SmartBftSetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the smart bft set params
func (o *SmartBftSetParams) WithTimeout(timeout time.Duration) *SmartBftSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the smart bft set params
func (o *SmartBftSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the smart bft set params
func (o *SmartBftSetParams) WithContext(ctx context.Context) *SmartBftSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the smart bft set params
func (o *SmartBftSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the smart bft set params
func (o *SmartBftSetParams) WithHTTPClient(client *http.Client) *SmartBftSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the smart bft set params
func (o *SmartBftSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the smart bft set params
func (o *SmartBftSetParams) WithBody(body SmartBftSetBody) *SmartBftSetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the smart bft set params
func (o *SmartBftSetParams) SetBody(body SmartBftSetBody) {
	o.Body = body
}

// WithChannelName adds the channelName to the smart bft set params
func (o *SmartBftSetParams) WithChannelName(channelName string) *SmartBftSetParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the smart bft set params
func (o *SmartBftSetParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *SmartBftSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
