// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/atomyze-foundation/hlf-control-plane/test/integration/models"
)

// SmartBftGetReader is a Reader for the SmartBftGet structure.
type SmartBftGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SmartBftGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSmartBftGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewSmartBftGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewSmartBftGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSmartBftGetOK creates a SmartBftGetOK with default headers values
func NewSmartBftGetOK() *SmartBftGetOK {
	return &SmartBftGetOK{}
}

/*
SmartBftGetOK describes a response with status code 200, with default header values.

A successful response.
*/
type SmartBftGetOK struct {
	Payload *models.ProtoConfigSmartBFTGetResponse
}

// IsSuccess returns true when this smart bft get o k response has a 2xx status code
func (o *SmartBftGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this smart bft get o k response has a 3xx status code
func (o *SmartBftGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smart bft get o k response has a 4xx status code
func (o *SmartBftGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this smart bft get o k response has a 5xx status code
func (o *SmartBftGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this smart bft get o k response a status code equal to that given
func (o *SmartBftGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the smart bft get o k response
func (o *SmartBftGetOK) Code() int {
	return 200
}

func (o *SmartBftGetOK) Error() string {
	return fmt.Sprintf("[GET /v1/config/{channelName}/smartbft][%d] smartBftGetOK  %+v", 200, o.Payload)
}

func (o *SmartBftGetOK) String() string {
	return fmt.Sprintf("[GET /v1/config/{channelName}/smartbft][%d] smartBftGetOK  %+v", 200, o.Payload)
}

func (o *SmartBftGetOK) GetPayload() *models.ProtoConfigSmartBFTGetResponse {
	return o.Payload
}

func (o *SmartBftGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoConfigSmartBFTGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSmartBftGetInternalServerError creates a SmartBftGetInternalServerError with default headers values
func NewSmartBftGetInternalServerError() *SmartBftGetInternalServerError {
	return &SmartBftGetInternalServerError{}
}

/*
SmartBftGetInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type SmartBftGetInternalServerError struct {
	Payload *models.ProtoErrorResponse
}

// IsSuccess returns true when this smart bft get internal server error response has a 2xx status code
func (o *SmartBftGetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smart bft get internal server error response has a 3xx status code
func (o *SmartBftGetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smart bft get internal server error response has a 4xx status code
func (o *SmartBftGetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this smart bft get internal server error response has a 5xx status code
func (o *SmartBftGetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this smart bft get internal server error response a status code equal to that given
func (o *SmartBftGetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the smart bft get internal server error response
func (o *SmartBftGetInternalServerError) Code() int {
	return 500
}

func (o *SmartBftGetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/config/{channelName}/smartbft][%d] smartBftGetInternalServerError  %+v", 500, o.Payload)
}

func (o *SmartBftGetInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/config/{channelName}/smartbft][%d] smartBftGetInternalServerError  %+v", 500, o.Payload)
}

func (o *SmartBftGetInternalServerError) GetPayload() *models.ProtoErrorResponse {
	return o.Payload
}

func (o *SmartBftGetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSmartBftGetDefault creates a SmartBftGetDefault with default headers values
func NewSmartBftGetDefault(code int) *SmartBftGetDefault {
	return &SmartBftGetDefault{
		_statusCode: code,
	}
}

/*
SmartBftGetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SmartBftGetDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this smart bft get default response has a 2xx status code
func (o *SmartBftGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this smart bft get default response has a 3xx status code
func (o *SmartBftGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this smart bft get default response has a 4xx status code
func (o *SmartBftGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this smart bft get default response has a 5xx status code
func (o *SmartBftGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this smart bft get default response a status code equal to that given
func (o *SmartBftGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the smart bft get default response
func (o *SmartBftGetDefault) Code() int {
	return o._statusCode
}

func (o *SmartBftGetDefault) Error() string {
	return fmt.Sprintf("[GET /v1/config/{channelName}/smartbft][%d] smartBftGet default  %+v", o._statusCode, o.Payload)
}

func (o *SmartBftGetDefault) String() string {
	return fmt.Sprintf("[GET /v1/config/{channelName}/smartbft][%d] smartBftGet default  %+v", o._statusCode, o.Payload)
}

func (o *SmartBftGetDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SmartBftGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
