// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.n-t.io/core/library/hlf-tool/hlf-control-plane/test/integration/models"
)

// ChannelCreateReader is a Reader for the ChannelCreate structure.
type ChannelCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChannelCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChannelCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewChannelCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewChannelCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewChannelCreateOK creates a ChannelCreateOK with default headers values
func NewChannelCreateOK() *ChannelCreateOK {
	return &ChannelCreateOK{}
}

/*
ChannelCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type ChannelCreateOK struct {
	Payload *models.ProtoChannelCreateResponse
}

// IsSuccess returns true when this channel create o k response has a 2xx status code
func (o *ChannelCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this channel create o k response has a 3xx status code
func (o *ChannelCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this channel create o k response has a 4xx status code
func (o *ChannelCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this channel create o k response has a 5xx status code
func (o *ChannelCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this channel create o k response a status code equal to that given
func (o *ChannelCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the channel create o k response
func (o *ChannelCreateOK) Code() int {
	return 200
}

func (o *ChannelCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1/channel/create][%d] channelCreateOK  %+v", 200, o.Payload)
}

func (o *ChannelCreateOK) String() string {
	return fmt.Sprintf("[POST /v1/channel/create][%d] channelCreateOK  %+v", 200, o.Payload)
}

func (o *ChannelCreateOK) GetPayload() *models.ProtoChannelCreateResponse {
	return o.Payload
}

func (o *ChannelCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoChannelCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChannelCreateInternalServerError creates a ChannelCreateInternalServerError with default headers values
func NewChannelCreateInternalServerError() *ChannelCreateInternalServerError {
	return &ChannelCreateInternalServerError{}
}

/*
ChannelCreateInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ChannelCreateInternalServerError struct {
	Payload *models.ProtoErrorResponse
}

// IsSuccess returns true when this channel create internal server error response has a 2xx status code
func (o *ChannelCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this channel create internal server error response has a 3xx status code
func (o *ChannelCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this channel create internal server error response has a 4xx status code
func (o *ChannelCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this channel create internal server error response has a 5xx status code
func (o *ChannelCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this channel create internal server error response a status code equal to that given
func (o *ChannelCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the channel create internal server error response
func (o *ChannelCreateInternalServerError) Code() int {
	return 500
}

func (o *ChannelCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/channel/create][%d] channelCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *ChannelCreateInternalServerError) String() string {
	return fmt.Sprintf("[POST /v1/channel/create][%d] channelCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *ChannelCreateInternalServerError) GetPayload() *models.ProtoErrorResponse {
	return o.Payload
}

func (o *ChannelCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChannelCreateDefault creates a ChannelCreateDefault with default headers values
func NewChannelCreateDefault(code int) *ChannelCreateDefault {
	return &ChannelCreateDefault{
		_statusCode: code,
	}
}

/*
ChannelCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ChannelCreateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this channel create default response has a 2xx status code
func (o *ChannelCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this channel create default response has a 3xx status code
func (o *ChannelCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this channel create default response has a 4xx status code
func (o *ChannelCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this channel create default response has a 5xx status code
func (o *ChannelCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this channel create default response a status code equal to that given
func (o *ChannelCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the channel create default response
func (o *ChannelCreateDefault) Code() int {
	return o._statusCode
}

func (o *ChannelCreateDefault) Error() string {
	return fmt.Sprintf("[POST /v1/channel/create][%d] channelCreate default  %+v", o._statusCode, o.Payload)
}

func (o *ChannelCreateDefault) String() string {
	return fmt.Sprintf("[POST /v1/channel/create][%d] channelCreate default  %+v", o._statusCode, o.Payload)
}

func (o *ChannelCreateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ChannelCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
