// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new channels API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for channels API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ChannelCreate(params *ChannelCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChannelCreateOK, error)

	ChannelJoin(params *ChannelJoinParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChannelJoinOK, error)

	ChannelsList(params *ChannelsListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChannelsListOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ChannelCreate creates channel genesis block and join orderers
*/
func (a *Client) ChannelCreate(params *ChannelCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChannelCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChannelCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "channelCreate",
		Method:             "POST",
		PathPattern:        "/v1/channel/create",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ChannelCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChannelCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ChannelCreateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ChannelJoin joins channel by fetching genesis block from orderer
*/
func (a *Client) ChannelJoin(params *ChannelJoinParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChannelJoinOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChannelJoinParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "channelJoin",
		Method:             "POST",
		PathPattern:        "/v1/channel/join",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ChannelJoinReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChannelJoinOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ChannelJoinDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ChannelsList gets list of joined channels
*/
func (a *Client) ChannelsList(params *ChannelsListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChannelsListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChannelsListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "channelsList",
		Method:             "GET",
		PathPattern:        "/v1/channel/joined",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ChannelsListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChannelsListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ChannelsListDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
