// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/atomyze-foundation/hlf-control-plane/test/integration/models"
)

// NewChannelJoinParams creates a new ChannelJoinParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChannelJoinParams() *ChannelJoinParams {
	return &ChannelJoinParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChannelJoinParamsWithTimeout creates a new ChannelJoinParams object
// with the ability to set a timeout on a request.
func NewChannelJoinParamsWithTimeout(timeout time.Duration) *ChannelJoinParams {
	return &ChannelJoinParams{
		timeout: timeout,
	}
}

// NewChannelJoinParamsWithContext creates a new ChannelJoinParams object
// with the ability to set a context for a request.
func NewChannelJoinParamsWithContext(ctx context.Context) *ChannelJoinParams {
	return &ChannelJoinParams{
		Context: ctx,
	}
}

// NewChannelJoinParamsWithHTTPClient creates a new ChannelJoinParams object
// with the ability to set a custom HTTPClient for a request.
func NewChannelJoinParamsWithHTTPClient(client *http.Client) *ChannelJoinParams {
	return &ChannelJoinParams{
		HTTPClient: client,
	}
}

/*
ChannelJoinParams contains all the parameters to send to the API endpoint

	for the channel join operation.

	Typically these are written to a http.Request.
*/
type ChannelJoinParams struct {

	// Body.
	Body *models.ProtoChannelJoinRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the channel join params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChannelJoinParams) WithDefaults() *ChannelJoinParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the channel join params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChannelJoinParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the channel join params
func (o *ChannelJoinParams) WithTimeout(timeout time.Duration) *ChannelJoinParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the channel join params
func (o *ChannelJoinParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the channel join params
func (o *ChannelJoinParams) WithContext(ctx context.Context) *ChannelJoinParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the channel join params
func (o *ChannelJoinParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the channel join params
func (o *ChannelJoinParams) WithHTTPClient(client *http.Client) *ChannelJoinParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the channel join params
func (o *ChannelJoinParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the channel join params
func (o *ChannelJoinParams) WithBody(body *models.ProtoChannelJoinRequest) *ChannelJoinParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the channel join params
func (o *ChannelJoinParams) SetBody(body *models.ProtoChannelJoinRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ChannelJoinParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
