// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/atomyze-foundation/hlf-control-plane/test/integration/models"
)

// NewChannelCreateParams creates a new ChannelCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChannelCreateParams() *ChannelCreateParams {
	return &ChannelCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChannelCreateParamsWithTimeout creates a new ChannelCreateParams object
// with the ability to set a timeout on a request.
func NewChannelCreateParamsWithTimeout(timeout time.Duration) *ChannelCreateParams {
	return &ChannelCreateParams{
		timeout: timeout,
	}
}

// NewChannelCreateParamsWithContext creates a new ChannelCreateParams object
// with the ability to set a context for a request.
func NewChannelCreateParamsWithContext(ctx context.Context) *ChannelCreateParams {
	return &ChannelCreateParams{
		Context: ctx,
	}
}

// NewChannelCreateParamsWithHTTPClient creates a new ChannelCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewChannelCreateParamsWithHTTPClient(client *http.Client) *ChannelCreateParams {
	return &ChannelCreateParams{
		HTTPClient: client,
	}
}

/*
ChannelCreateParams contains all the parameters to send to the API endpoint

	for the channel create operation.

	Typically these are written to a http.Request.
*/
type ChannelCreateParams struct {

	// Body.
	Body *models.ProtoChannelCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the channel create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChannelCreateParams) WithDefaults() *ChannelCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the channel create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChannelCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the channel create params
func (o *ChannelCreateParams) WithTimeout(timeout time.Duration) *ChannelCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the channel create params
func (o *ChannelCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the channel create params
func (o *ChannelCreateParams) WithContext(ctx context.Context) *ChannelCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the channel create params
func (o *ChannelCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the channel create params
func (o *ChannelCreateParams) WithHTTPClient(client *http.Client) *ChannelCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the channel create params
func (o *ChannelCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the channel create params
func (o *ChannelCreateParams) WithBody(body *models.ProtoChannelCreateRequest) *ChannelCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the channel create params
func (o *ChannelCreateParams) SetBody(body *models.ProtoChannelCreateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ChannelCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
