// Code generated by go-swagger; DO NOT EDIT.

package lifecycle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/atomyze-foundation/hlf-control-plane/test/integration/models"
)

// NewLifecycleFullParams creates a new LifecycleFullParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLifecycleFullParams() *LifecycleFullParams {
	return &LifecycleFullParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLifecycleFullParamsWithTimeout creates a new LifecycleFullParams object
// with the ability to set a timeout on a request.
func NewLifecycleFullParamsWithTimeout(timeout time.Duration) *LifecycleFullParams {
	return &LifecycleFullParams{
		timeout: timeout,
	}
}

// NewLifecycleFullParamsWithContext creates a new LifecycleFullParams object
// with the ability to set a context for a request.
func NewLifecycleFullParamsWithContext(ctx context.Context) *LifecycleFullParams {
	return &LifecycleFullParams{
		Context: ctx,
	}
}

// NewLifecycleFullParamsWithHTTPClient creates a new LifecycleFullParams object
// with the ability to set a custom HTTPClient for a request.
func NewLifecycleFullParamsWithHTTPClient(client *http.Client) *LifecycleFullParams {
	return &LifecycleFullParams{
		HTTPClient: client,
	}
}

/*
LifecycleFullParams contains all the parameters to send to the API endpoint

	for the lifecycle full operation.

	Typically these are written to a http.Request.
*/
type LifecycleFullParams struct {

	// Body.
	Body *models.ProtoLifecycleFullRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lifecycle full params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LifecycleFullParams) WithDefaults() *LifecycleFullParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lifecycle full params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LifecycleFullParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lifecycle full params
func (o *LifecycleFullParams) WithTimeout(timeout time.Duration) *LifecycleFullParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lifecycle full params
func (o *LifecycleFullParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lifecycle full params
func (o *LifecycleFullParams) WithContext(ctx context.Context) *LifecycleFullParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lifecycle full params
func (o *LifecycleFullParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lifecycle full params
func (o *LifecycleFullParams) WithHTTPClient(client *http.Client) *LifecycleFullParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lifecycle full params
func (o *LifecycleFullParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the lifecycle full params
func (o *LifecycleFullParams) WithBody(body *models.ProtoLifecycleFullRequest) *LifecycleFullParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the lifecycle full params
func (o *LifecycleFullParams) SetBody(body *models.ProtoLifecycleFullRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *LifecycleFullParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
