// Code generated by go-swagger; DO NOT EDIT.

package lifecycle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLifecycleStatusParams creates a new LifecycleStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLifecycleStatusParams() *LifecycleStatusParams {
	return &LifecycleStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLifecycleStatusParamsWithTimeout creates a new LifecycleStatusParams object
// with the ability to set a timeout on a request.
func NewLifecycleStatusParamsWithTimeout(timeout time.Duration) *LifecycleStatusParams {
	return &LifecycleStatusParams{
		timeout: timeout,
	}
}

// NewLifecycleStatusParamsWithContext creates a new LifecycleStatusParams object
// with the ability to set a context for a request.
func NewLifecycleStatusParamsWithContext(ctx context.Context) *LifecycleStatusParams {
	return &LifecycleStatusParams{
		Context: ctx,
	}
}

// NewLifecycleStatusParamsWithHTTPClient creates a new LifecycleStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewLifecycleStatusParamsWithHTTPClient(client *http.Client) *LifecycleStatusParams {
	return &LifecycleStatusParams{
		HTTPClient: client,
	}
}

/*
LifecycleStatusParams contains all the parameters to send to the API endpoint

	for the lifecycle status operation.

	Typically these are written to a http.Request.
*/
type LifecycleStatusParams struct {

	// ChannelName.
	ChannelName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lifecycle status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LifecycleStatusParams) WithDefaults() *LifecycleStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lifecycle status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LifecycleStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lifecycle status params
func (o *LifecycleStatusParams) WithTimeout(timeout time.Duration) *LifecycleStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lifecycle status params
func (o *LifecycleStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lifecycle status params
func (o *LifecycleStatusParams) WithContext(ctx context.Context) *LifecycleStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lifecycle status params
func (o *LifecycleStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lifecycle status params
func (o *LifecycleStatusParams) WithHTTPClient(client *http.Client) *LifecycleStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lifecycle status params
func (o *LifecycleStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelName adds the channelName to the lifecycle status params
func (o *LifecycleStatusParams) WithChannelName(channelName string) *LifecycleStatusParams {
	o.SetChannelName(channelName)
	return o
}

// SetChannelName adds the channelName to the lifecycle status params
func (o *LifecycleStatusParams) SetChannelName(channelName string) {
	o.ChannelName = channelName
}

// WriteToRequest writes these params to a swagger request
func (o *LifecycleStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channelName
	if err := r.SetPathParam("channelName", o.ChannelName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
