// Code generated by go-swagger; DO NOT EDIT.

package lifecycle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gitlab.n-t.io/core/library/hlf-tool/hlf-control-plane/test/integration/models"
)

// NewLifecycleInitParams creates a new LifecycleInitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLifecycleInitParams() *LifecycleInitParams {
	return &LifecycleInitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLifecycleInitParamsWithTimeout creates a new LifecycleInitParams object
// with the ability to set a timeout on a request.
func NewLifecycleInitParamsWithTimeout(timeout time.Duration) *LifecycleInitParams {
	return &LifecycleInitParams{
		timeout: timeout,
	}
}

// NewLifecycleInitParamsWithContext creates a new LifecycleInitParams object
// with the ability to set a context for a request.
func NewLifecycleInitParamsWithContext(ctx context.Context) *LifecycleInitParams {
	return &LifecycleInitParams{
		Context: ctx,
	}
}

// NewLifecycleInitParamsWithHTTPClient creates a new LifecycleInitParams object
// with the ability to set a custom HTTPClient for a request.
func NewLifecycleInitParamsWithHTTPClient(client *http.Client) *LifecycleInitParams {
	return &LifecycleInitParams{
		HTTPClient: client,
	}
}

/*
LifecycleInitParams contains all the parameters to send to the API endpoint

	for the lifecycle init operation.

	Typically these are written to a http.Request.
*/
type LifecycleInitParams struct {

	// Body.
	Body *models.ProtoLifecycleInitRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lifecycle init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LifecycleInitParams) WithDefaults() *LifecycleInitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lifecycle init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LifecycleInitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lifecycle init params
func (o *LifecycleInitParams) WithTimeout(timeout time.Duration) *LifecycleInitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lifecycle init params
func (o *LifecycleInitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lifecycle init params
func (o *LifecycleInitParams) WithContext(ctx context.Context) *LifecycleInitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lifecycle init params
func (o *LifecycleInitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lifecycle init params
func (o *LifecycleInitParams) WithHTTPClient(client *http.Client) *LifecycleInitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lifecycle init params
func (o *LifecycleInitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the lifecycle init params
func (o *LifecycleInitParams) WithBody(body *models.ProtoLifecycleInitRequest) *LifecycleInitParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the lifecycle init params
func (o *LifecycleInitParams) SetBody(body *models.ProtoLifecycleInitRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *LifecycleInitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
