// Code generated by go-swagger; DO NOT EDIT.

package lifecycle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.n-t.io/core/library/hlf-tool/hlf-control-plane/test/integration/models"
)

// LifecycleInitReader is a Reader for the LifecycleInit structure.
type LifecycleInitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LifecycleInitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLifecycleInitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewLifecycleInitInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewLifecycleInitDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLifecycleInitOK creates a LifecycleInitOK with default headers values
func NewLifecycleInitOK() *LifecycleInitOK {
	return &LifecycleInitOK{}
}

/*
LifecycleInitOK describes a response with status code 200, with default header values.

A successful response.
*/
type LifecycleInitOK struct {
	Payload models.ProtoLifecycleInitResponse
}

// IsSuccess returns true when this lifecycle init o k response has a 2xx status code
func (o *LifecycleInitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this lifecycle init o k response has a 3xx status code
func (o *LifecycleInitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lifecycle init o k response has a 4xx status code
func (o *LifecycleInitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this lifecycle init o k response has a 5xx status code
func (o *LifecycleInitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this lifecycle init o k response a status code equal to that given
func (o *LifecycleInitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the lifecycle init o k response
func (o *LifecycleInitOK) Code() int {
	return 200
}

func (o *LifecycleInitOK) Error() string {
	return fmt.Sprintf("[POST /v1/lifecycle/init][%d] lifecycleInitOK  %+v", 200, o.Payload)
}

func (o *LifecycleInitOK) String() string {
	return fmt.Sprintf("[POST /v1/lifecycle/init][%d] lifecycleInitOK  %+v", 200, o.Payload)
}

func (o *LifecycleInitOK) GetPayload() models.ProtoLifecycleInitResponse {
	return o.Payload
}

func (o *LifecycleInitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLifecycleInitInternalServerError creates a LifecycleInitInternalServerError with default headers values
func NewLifecycleInitInternalServerError() *LifecycleInitInternalServerError {
	return &LifecycleInitInternalServerError{}
}

/*
LifecycleInitInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type LifecycleInitInternalServerError struct {
	Payload *models.ProtoErrorResponse
}

// IsSuccess returns true when this lifecycle init internal server error response has a 2xx status code
func (o *LifecycleInitInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lifecycle init internal server error response has a 3xx status code
func (o *LifecycleInitInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lifecycle init internal server error response has a 4xx status code
func (o *LifecycleInitInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this lifecycle init internal server error response has a 5xx status code
func (o *LifecycleInitInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this lifecycle init internal server error response a status code equal to that given
func (o *LifecycleInitInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the lifecycle init internal server error response
func (o *LifecycleInitInternalServerError) Code() int {
	return 500
}

func (o *LifecycleInitInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/lifecycle/init][%d] lifecycleInitInternalServerError  %+v", 500, o.Payload)
}

func (o *LifecycleInitInternalServerError) String() string {
	return fmt.Sprintf("[POST /v1/lifecycle/init][%d] lifecycleInitInternalServerError  %+v", 500, o.Payload)
}

func (o *LifecycleInitInternalServerError) GetPayload() *models.ProtoErrorResponse {
	return o.Payload
}

func (o *LifecycleInitInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLifecycleInitDefault creates a LifecycleInitDefault with default headers values
func NewLifecycleInitDefault(code int) *LifecycleInitDefault {
	return &LifecycleInitDefault{
		_statusCode: code,
	}
}

/*
LifecycleInitDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type LifecycleInitDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this lifecycle init default response has a 2xx status code
func (o *LifecycleInitDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this lifecycle init default response has a 3xx status code
func (o *LifecycleInitDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this lifecycle init default response has a 4xx status code
func (o *LifecycleInitDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this lifecycle init default response has a 5xx status code
func (o *LifecycleInitDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this lifecycle init default response a status code equal to that given
func (o *LifecycleInitDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the lifecycle init default response
func (o *LifecycleInitDefault) Code() int {
	return o._statusCode
}

func (o *LifecycleInitDefault) Error() string {
	return fmt.Sprintf("[POST /v1/lifecycle/init][%d] lifecycleInit default  %+v", o._statusCode, o.Payload)
}

func (o *LifecycleInitDefault) String() string {
	return fmt.Sprintf("[POST /v1/lifecycle/init][%d] lifecycleInit default  %+v", o._statusCode, o.Payload)
}

func (o *LifecycleInitDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *LifecycleInitDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
